language: scala

jdk:
  - openjdk11

jobs:
  include:
    - stage: Compile
      name: Compile
      script:
        - sbt compile
    - stage: Tests
      name: Unit tests
      script:
        - sbt compile test